/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2026-10-02 02:25:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.usermgmt.model.User;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("com.usermgmt.model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    // Server-side session verification guard
    User sessionUser = (User) session.getAttribute("LOGGED_IN_USER");
    if (sessionUser == null) {
        response.sendRedirect(request.getContextPath() + "/login.jsp?sessionExpired=true");
        return;
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <meta name=\"description\" content=\"User Management Dashboard with CRUD, Grid, and Session Security\">\n");
      out.write("    <title>Dashboard &mdash; User Management System</title>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap 5.3 CSS -->\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- Bootstrap Icons -->\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- Custom Modern Styling -->\n");
      out.write("    <link href=\"assets/css/custom.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <!-- Sticky Navigation Bar -->\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-custom\">\n");
      out.write("        <div class=\"container-fluid px-lg-4\">\n");
      out.write("            <!-- Brand -->\n");
      out.write("            <a class=\"navbar-brand\" href=\"home.jsp\">\n");
      out.write("                <span class=\"logo-badge\"><i class=\"bi bi-people-fill\"></i></span>\n");
      out.write("                <div>\n");
      out.write("                    <div class=\"lh-1 brand-font\">UserSphere</div>\n");
      out.write("                    <span class=\"small text-muted fw-normal\" style=\"font-size: 0.72rem;\">Enterprise Directory</span>\n");
      out.write("                </div>\n");
      out.write("            </a>\n");
      out.write("\n");
      out.write("            <!-- Right Controls: DB status, user profile & logout -->\n");
      out.write("            <div class=\"d-flex align-items-center gap-3 ms-auto\">\n");
      out.write("                <!-- Database Engine Indicator -->\n");
      out.write("                <span id=\"dbEngineBadge\" class=\"badge bg-success-subtle text-success border border-success-subtle d-none d-md-inline-flex align-items-center py-2 px-3 rounded-pill small\">\n");
      out.write("                    <i class=\"bi bi-database-check me-1\"></i>MySQL Connected\n");
      out.write("                </span>\n");
      out.write("\n");
      out.write("                <!-- Current User Profile Pill -->\n");
      out.write("                <div class=\"user-profile-badge\">\n");
      out.write("                    <div class=\"avatar-circle\" id=\"currentUserAvatar\">\n");
      out.write("                        ");
      out.print( sessionUser.getFullName() != null && sessionUser.getFullName().length() >= 2 ? sessionUser.getFullName().substring(0, 2).toUpperCase() : "US" );
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"d-none d-sm-block text-start lh-sm pe-1\">\n");
      out.write("                        <div class=\"fw-bold small\" id=\"currentUserName\">");
      out.print( sessionUser.getFullName() );
      out.write("</div>\n");
      out.write("                        <span class=\"badge bg-primary-subtle text-primary\" style=\"font-size: 0.65rem;\" id=\"currentUserRole\">");
      out.print( sessionUser.getRole() );
      out.write("</span>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- Logout Button -->\n");
      out.write("                <button type=\"button\" id=\"btnLogout\" class=\"btn btn-outline-danger btn-sm rounded-pill px-3 py-1 d-flex align-items-center gap-1 shadow-sm\" title=\"End Current Session\">\n");
      out.write("                    <i class=\"bi bi-box-arrow-right\"></i>\n");
      out.write("                    <span class=\"d-none d-sm-inline\">Sign Out</span>\n");
      out.write("                </button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <!-- Main Container -->\n");
      out.write("    <main class=\"container-fluid px-lg-5 py-4\">\n");
      out.write("\n");
      out.write("        <!-- Top Welcome & KPIs Section -->\n");
      out.write("        <div class=\"row g-3 mb-4\">\n");
      out.write("            <!-- Total Users -->\n");
      out.write("            <div class=\"col-12 col-sm-6 col-xl-3\">\n");
      out.write("                <div class=\"stat-card primary\">\n");
      out.write("                    <div class=\"d-flex justify-content-between align-items-start\">\n");
      out.write("                        <div>\n");
      out.write("                            <span class=\"text-secondary small fw-semibold text-uppercase\">Total Users</span>\n");
      out.write("                            <div class=\"stat-value text-dark\" id=\"statTotalUsers\">0</div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"stat-icon\"><i class=\"bi bi-people\"></i></div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"mt-2 small text-muted\"><i class=\"bi bi-info-circle me-1\"></i>Registered directory accounts</div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Active Users -->\n");
      out.write("            <div class=\"col-12 col-sm-6 col-xl-3\">\n");
      out.write("                <div class=\"stat-card success\">\n");
      out.write("                    <div class=\"d-flex justify-content-between align-items-start\">\n");
      out.write("                        <div>\n");
      out.write("                            <span class=\"text-secondary small fw-semibold text-uppercase\">Active Accounts</span>\n");
      out.write("                            <div class=\"stat-value text-dark\" id=\"statActiveUsers\">0</div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"stat-icon\"><i class=\"bi bi-check2-circle\"></i></div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"mt-2 small text-muted\"><i class=\"bi bi-shield-check me-1 text-success\"></i>Operational & authorized</div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Inactive Users -->\n");
      out.write("            <div class=\"col-12 col-sm-6 col-xl-3\">\n");
      out.write("                <div class=\"stat-card warning\">\n");
      out.write("                    <div class=\"d-flex justify-content-between align-items-start\">\n");
      out.write("                        <div>\n");
      out.write("                            <span class=\"text-secondary small fw-semibold text-uppercase\">Inactive / Suspended</span>\n");
      out.write("                            <div class=\"stat-value text-dark\" id=\"statInactiveUsers\">0</div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"stat-icon\"><i class=\"bi bi-pause-circle\"></i></div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"mt-2 small text-muted\"><i class=\"bi bi-lock me-1 text-warning\"></i>Login access restricted</div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Administrators -->\n");
      out.write("            <div class=\"col-12 col-sm-6 col-xl-3\">\n");
      out.write("                <div class=\"stat-card info\">\n");
      out.write("                    <div class=\"d-flex justify-content-between align-items-start\">\n");
      out.write("                        <div>\n");
      out.write("                            <span class=\"text-secondary small fw-semibold text-uppercase\">Admins & Managers</span>\n");
      out.write("                            <div class=\"stat-value text-dark\" id=\"statAdminUsers\">0</div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"stat-icon\"><i class=\"bi bi-shield-shaded\"></i></div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"mt-2 small text-muted\"><i class=\"bi bi-key me-1 text-primary\"></i>Elevated governance roles</div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Main Card: User Management Grid -->\n");
      out.write("        <div class=\"main-card\">\n");
      out.write("            <!-- Header Controls -->\n");
      out.write("            <div class=\"main-card-header\">\n");
      out.write("                <div>\n");
      out.write("                    <h5 class=\"fw-bold mb-0 brand-font text-dark\">Directory Users</h5>\n");
      out.write("                    <small class=\"text-muted\" id=\"totalUsersCountDisplay\">Loading user records...</small>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"d-flex flex-wrap align-items-center gap-2\">\n");
      out.write("                    <!-- Search Input -->\n");
      out.write("                    <div class=\"input-group input-group-sm\" style=\"max-width: 260px;\">\n");
      out.write("                        <span class=\"input-group-text bg-white border-end-0 text-muted\"><i class=\"bi bi-search\"></i></span>\n");
      out.write("                        <input type=\"text\" class=\"form-control border-start-0 ps-0\" id=\"searchInput\" placeholder=\"Search by name, email, user...\">\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <!-- Role Filter -->\n");
      out.write("                    <select class=\"form-select form-select-sm\" id=\"roleFilter\" style=\"width: auto;\">\n");
      out.write("                        <option value=\"ALL\">All Roles</option>\n");
      out.write("                        <option value=\"ADMIN\">Admin</option>\n");
      out.write("                        <option value=\"MANAGER\">Manager</option>\n");
      out.write("                        <option value=\"USER\">User</option>\n");
      out.write("                    </select>\n");
      out.write("\n");
      out.write("                    <!-- Status Filter -->\n");
      out.write("                    <select class=\"form-select form-select-sm\" id=\"statusFilter\" style=\"width: auto;\">\n");
      out.write("                        <option value=\"ALL\">All Statuses</option>\n");
      out.write("                        <option value=\"ACTIVE\">Active</option>\n");
      out.write("                        <option value=\"INACTIVE\">Inactive</option>\n");
      out.write("                        <option value=\"SUSPENDED\">Suspended</option>\n");
      out.write("                    </select>\n");
      out.write("\n");
      out.write("                    <!-- Refresh Button -->\n");
      out.write("                    <button type=\"button\" class=\"btn btn-outline-secondary btn-sm rounded-3\" id=\"btnRefresh\" title=\"Refresh Table\">\n");
      out.write("                        <i class=\"bi bi-arrow-clockwise\"></i>\n");
      out.write("                    </button>\n");
      out.write("\n");
      out.write("                    <!-- Add User Button -->\n");
      out.write("                    <button type=\"button\" class=\"btn btn-primary btn-sm rounded-3 d-flex align-items-center gap-1 shadow-sm\" id=\"btnAddUser\">\n");
      out.write("                        <i class=\"bi bi-person-plus-fill\"></i>\n");
      out.write("                        <span>Add User</span>\n");
      out.write("                    </button>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Table Grid -->\n");
      out.write("            <div class=\"table-responsive\">\n");
      out.write("                <table class=\"table table-custom table-hover align-middle\">\n");
      out.write("                    <thead>\n");
      out.write("                        <tr>\n");
      out.write("                            <th scope=\"col\" style=\"width: 80px;\">ID</th>\n");
      out.write("                            <th scope=\"col\">User</th>\n");
      out.write("                            <th scope=\"col\">Email Address</th>\n");
      out.write("                            <th scope=\"col\">Department</th>\n");
      out.write("                            <th scope=\"col\">Role</th>\n");
      out.write("                            <th scope=\"col\">Status</th>\n");
      out.write("                            <th scope=\"col\" class=\"text-end\" style=\"width: 140px;\">Actions</th>\n");
      out.write("                        </tr>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody id=\"usersTableBody\">\n");
      out.write("                        <!-- Populated dynamically via Ajax -->\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Card Footer: Pagination & Page Size -->\n");
      out.write("            <div class=\"p-3 border-top bg-light d-flex flex-wrap justify-content-between align-items-center gap-3\">\n");
      out.write("                <div class=\"d-flex align-items-center gap-2\">\n");
      out.write("                    <span class=\"small text-muted\">Rows per page:</span>\n");
      out.write("                    <select class=\"form-select form-select-sm\" id=\"pageSizeSelect\" style=\"width: 70px;\">\n");
      out.write("                        <option value=\"5\">5</option>\n");
      out.write("                        <option value=\"10\" selected>10</option>\n");
      out.write("                        <option value=\"25\">25</option>\n");
      out.write("                        <option value=\"50\">50</option>\n");
      out.write("                    </select>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- Pagination Nav -->\n");
      out.write("                <nav aria-label=\"Users pagination\">\n");
      out.write("                    <ul class=\"pagination pagination-sm mb-0\" id=\"paginationContainer\">\n");
      out.write("                        <!-- Dynamic page links -->\n");
      out.write("                    </ul>\n");
      out.write("                </nav>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </main>\n");
      out.write("\n");
      out.write("    <!-- ====================================================================\n");
      out.write("         MODALS\n");
      out.write("         ==================================================================== -->\n");
      out.write("\n");
      out.write("    <!-- 1. Add User Modal -->\n");
      out.write("    <div class=\"modal fade\" id=\"addUserModal\" tabindex=\"-1\" aria-labelledby=\"addUserModalLabel\" aria-hidden=\"true\">\n");
      out.write("        <div class=\"modal-dialog modal-dialog-centered\">\n");
      out.write("            <div class=\"modal-content\">\n");
      out.write("                <div class=\"modal-header\">\n");
      out.write("                    <h5 class=\"modal-title fw-bold\" id=\"addUserModalLabel\"><i class=\"bi bi-person-plus me-2 text-primary\"></i>Add New User</h5>\n");
      out.write("                    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"modal-body\">\n");
      out.write("                    <div id=\"addUserAlert\" class=\"alert d-none py-2 px-3 small\"></div>\n");
      out.write("                    <form id=\"addUserForm\">\n");
      out.write("                        <div class=\"row g-3\">\n");
      out.write("                            <div class=\"col-md-6\">\n");
      out.write("                                <label for=\"addUsername\" class=\"form-label small fw-semibold\">Username *</label>\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"addUsername\" required placeholder=\"e.g. alex_stone\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-md-6\">\n");
      out.write("                                <label for=\"addFullName\" class=\"form-label small fw-semibold\">Full Name *</label>\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"addFullName\" required placeholder=\"e.g. Alex Stone\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-12\">\n");
      out.write("                                <label for=\"addEmail\" class=\"form-label small fw-semibold\">Email Address *</label>\n");
      out.write("                                <input type=\"email\" class=\"form-control\" id=\"addEmail\" required placeholder=\"alex@company.com\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-12\">\n");
      out.write("                                <label for=\"addPassword\" class=\"form-label small fw-semibold\">Temporary Password *</label>\n");
      out.write("                                <input type=\"password\" class=\"form-control\" id=\"addPassword\" required placeholder=\"Minimum 6 characters\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-md-6\">\n");
      out.write("                                <label for=\"addRole\" class=\"form-label small fw-semibold\">Role *</label>\n");
      out.write("                                <select class=\"form-select\" id=\"addRole\">\n");
      out.write("                                    <option value=\"USER\" selected>User</option>\n");
      out.write("                                    <option value=\"MANAGER\">Manager</option>\n");
      out.write("                                    <option value=\"ADMIN\">Administrator</option>\n");
      out.write("                                </select>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-md-6\">\n");
      out.write("                                <label for=\"addStatus\" class=\"form-label small fw-semibold\">Status *</label>\n");
      out.write("                                <select class=\"form-select\" id=\"addStatus\">\n");
      out.write("                                    <option value=\"ACTIVE\" selected>Active</option>\n");
      out.write("                                    <option value=\"INACTIVE\">Inactive</option>\n");
      out.write("                                </select>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-md-6\">\n");
      out.write("                                <label for=\"addPhone\" class=\"form-label small fw-semibold\">Phone</label>\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"addPhone\" placeholder=\"+1-555-0100\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-md-6\">\n");
      out.write("                                <label for=\"addDepartment\" class=\"form-label small fw-semibold\">Department</label>\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"addDepartment\" placeholder=\"Engineering\">\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"modal-footer\">\n");
      out.write("                    <button type=\"button\" class=\"btn btn-light\" data-bs-dismiss=\"modal\">Cancel</button>\n");
      out.write("                    <button type=\"button\" class=\"btn btn-primary\" id=\"saveAddUserBtn\">\n");
      out.write("                        <i class=\"bi bi-check2-circle me-1\"></i>Create User\n");
      out.write("                    </button>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- 2. Edit User Modal -->\n");
      out.write("    <div class=\"modal fade\" id=\"editUserModal\" tabindex=\"-1\" aria-labelledby=\"editUserModalLabel\" aria-hidden=\"true\">\n");
      out.write("        <div class=\"modal-dialog modal-dialog-centered\">\n");
      out.write("            <div class=\"modal-content\">\n");
      out.write("                <div class=\"modal-header\">\n");
      out.write("                    <h5 class=\"modal-title fw-bold\" id=\"editUserModalLabel\"><i class=\"bi bi-pencil-square me-2 text-primary\"></i>Update User Record</h5>\n");
      out.write("                    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"modal-body\">\n");
      out.write("                    <div id=\"editUserAlert\" class=\"alert d-none py-2 px-3 small\"></div>\n");
      out.write("                    <form id=\"editUserForm\">\n");
      out.write("                        <input type=\"hidden\" id=\"editUserId\">\n");
      out.write("                        <div class=\"row g-3\">\n");
      out.write("                            <div class=\"col-md-6\">\n");
      out.write("                                <label for=\"editUsername\" class=\"form-label small fw-semibold\">Username</label>\n");
      out.write("                                <input type=\"text\" class=\"form-control bg-light\" id=\"editUsername\" readonly disabled>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-md-6\">\n");
      out.write("                                <label for=\"editFullName\" class=\"form-label small fw-semibold\">Full Name *</label>\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"editFullName\" required>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-12\">\n");
      out.write("                                <label for=\"editEmail\" class=\"form-label small fw-semibold\">Email Address *</label>\n");
      out.write("                                <input type=\"email\" class=\"form-control\" id=\"editEmail\" required>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-md-6\">\n");
      out.write("                                <label for=\"editRole\" class=\"form-label small fw-semibold\">Role</label>\n");
      out.write("                                <select class=\"form-select\" id=\"editRole\">\n");
      out.write("                                    <option value=\"USER\">User</option>\n");
      out.write("                                    <option value=\"MANAGER\">Manager</option>\n");
      out.write("                                    <option value=\"ADMIN\">Administrator</option>\n");
      out.write("                                </select>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-md-6\">\n");
      out.write("                                <label for=\"editStatus\" class=\"form-label small fw-semibold\">Status</label>\n");
      out.write("                                <select class=\"form-select\" id=\"editStatus\">\n");
      out.write("                                    <option value=\"ACTIVE\">Active</option>\n");
      out.write("                                    <option value=\"INACTIVE\">Inactive</option>\n");
      out.write("                                    <option value=\"SUSPENDED\">Suspended</option>\n");
      out.write("                                </select>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-md-6\">\n");
      out.write("                                <label for=\"editPhone\" class=\"form-label small fw-semibold\">Phone</label>\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"editPhone\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-md-6\">\n");
      out.write("                                <label for=\"editDepartment\" class=\"form-label small fw-semibold\">Department</label>\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"editDepartment\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-12\">\n");
      out.write("                                <label for=\"editPassword\" class=\"form-label small fw-semibold\">Reset Password (Optional)</label>\n");
      out.write("                                <input type=\"password\" class=\"form-control\" id=\"editPassword\" placeholder=\"Leave blank to keep current password\">\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"modal-footer\">\n");
      out.write("                    <button type=\"button\" class=\"btn btn-light\" data-bs-dismiss=\"modal\">Cancel</button>\n");
      out.write("                    <button type=\"button\" class=\"btn btn-primary\" id=\"saveEditUserBtn\">\n");
      out.write("                        <i class=\"bi bi-save me-1\"></i>Save Changes\n");
      out.write("                    </button>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- 3. View User Profile Modal -->\n");
      out.write("    <div class=\"modal fade\" id=\"viewUserModal\" tabindex=\"-1\" aria-labelledby=\"viewUserModalLabel\" aria-hidden=\"true\">\n");
      out.write("        <div class=\"modal-dialog modal-dialog-centered\">\n");
      out.write("            <div class=\"modal-content\">\n");
      out.write("                <div class=\"modal-header\">\n");
      out.write("                    <h5 class=\"modal-title fw-bold\" id=\"viewUserModalLabel\"><i class=\"bi bi-person-badge me-2 text-primary\"></i>User Profile</h5>\n");
      out.write("                    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"modal-body text-center pt-4\">\n");
      out.write("                    <div class=\"avatar-circle mx-auto mb-3\" id=\"viewAvatar\" style=\"width: 64px; height: 64px; font-size: 1.5rem;\">US</div>\n");
      out.write("                    <h4 class=\"fw-bold mb-1\" id=\"viewFullName\">User Full Name</h4>\n");
      out.write("                    <p class=\"text-muted small mb-3\" id=\"viewUsername\">@username</p>\n");
      out.write("\n");
      out.write("                    <div class=\"text-start bg-light p-3 rounded-3 small\">\n");
      out.write("                        <div class=\"row g-2\">\n");
      out.write("                            <div class=\"col-4 text-secondary\">Email:</div>\n");
      out.write("                            <div class=\"col-8 fw-semibold\" id=\"viewEmail\">—</div>\n");
      out.write("\n");
      out.write("                            <div class=\"col-4 text-secondary\">Department:</div>\n");
      out.write("                            <div class=\"col-8 fw-semibold\" id=\"viewDepartment\">—</div>\n");
      out.write("\n");
      out.write("                            <div class=\"col-4 text-secondary\">Phone:</div>\n");
      out.write("                            <div class=\"col-8 fw-semibold\" id=\"viewPhone\">—</div>\n");
      out.write("\n");
      out.write("                            <div class=\"col-4 text-secondary\">Role:</div>\n");
      out.write("                            <div class=\"col-8 fw-semibold\" id=\"viewRole\">—</div>\n");
      out.write("\n");
      out.write("                            <div class=\"col-4 text-secondary\">Status:</div>\n");
      out.write("                            <div class=\"col-8 fw-semibold\" id=\"viewStatus\">—</div>\n");
      out.write("\n");
      out.write("                            <div class=\"col-4 text-secondary\">Joined:</div>\n");
      out.write("                            <div class=\"col-8 fw-semibold\" id=\"viewCreatedAt\">—</div>\n");
      out.write("\n");
      out.write("                            <div class=\"col-4 text-secondary\">Updated:</div>\n");
      out.write("                            <div class=\"col-8 fw-semibold\" id=\"viewUpdatedAt\">—</div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"modal-footer\">\n");
      out.write("                    <button type=\"button\" class=\"btn btn-secondary btn-sm\" data-bs-dismiss=\"modal\">Close</button>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- 4. Delete Confirmation Modal -->\n");
      out.write("    <div class=\"modal fade\" id=\"deleteUserModal\" tabindex=\"-1\" aria-labelledby=\"deleteUserModalLabel\" aria-hidden=\"true\">\n");
      out.write("        <div class=\"modal-dialog modal-dialog-centered modal-sm\">\n");
      out.write("            <div class=\"modal-content\">\n");
      out.write("                <div class=\"modal-header border-0 pb-0\">\n");
      out.write("                    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"modal-body text-center pt-0\">\n");
      out.write("                    <div class=\"text-danger mb-3\">\n");
      out.write("                        <i class=\"bi bi-exclamation-triangle-fill\" style=\"font-size: 3rem;\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <h5 class=\"fw-bold mb-2\">Delete User?</h5>\n");
      out.write("                    <p class=\"text-muted small mb-3\">Are you sure you want to permanently delete user <strong id=\"deleteTargetName\">@user</strong>? This action cannot be undone.</p>\n");
      out.write("                    <div id=\"deleteAlert\" class=\"alert d-none py-2 px-3 small text-start\"></div>\n");
      out.write("                    <input type=\"hidden\" id=\"deleteUserId\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"modal-footer border-0 justify-content-center pt-0 pb-3\">\n");
      out.write("                    <button type=\"button\" class=\"btn btn-light btn-sm\" data-bs-dismiss=\"modal\">Cancel</button>\n");
      out.write("                    <button type=\"button\" class=\"btn btn-danger btn-sm px-3\" id=\"confirmDeleteBtn\">Delete Permanently</button>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Toast Notification Container -->\n");
      out.write("    <div class=\"toast-container\" id=\"toastContainer\"></div>\n");
      out.write("\n");
      out.write("    <!-- jQuery 3.7.1 -->\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.7.1.min.js\"></script>\n");
      out.write("    <!-- Bootstrap 5.3 JS Bundle -->\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("    <!-- Application Logic -->\n");
      out.write("    <script src=\"assets/js/app.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
