/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2026-10-02 02:24:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <meta name=\"description\" content=\"Secure Session-based Login for Enterprise User Management System\">\n");
      out.write("    <title>Sign In &mdash; User Management System</title>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap 5.3 CSS -->\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- Bootstrap Icons -->\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- Custom Modern Styling -->\n");
      out.write("    <link href=\"assets/css/custom.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body class=\"login-body\">\n");
      out.write("\n");
      out.write("    <div class=\"login-card\">\n");
      out.write("        <!-- Header -->\n");
      out.write("        <div class=\"login-header\">\n");
      out.write("            <div class=\"brand-icon\">\n");
      out.write("                <i class=\"bi bi-shield-lock-fill\"></i>\n");
      out.write("            </div>\n");
      out.write("            <h3 class=\"fw-bold mb-1 brand-font\">Enterprise Portal</h3>\n");
      out.write("            <p class=\"mb-0 text-white-50 small\">Session-Based Secure Authentication</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Body -->\n");
      out.write("        <div class=\"login-body-content\">\n");
      out.write("            <!-- Alert message container -->\n");
      out.write("            <div id=\"loginAlert\" class=\"alert d-none py-2 px-3 small\" role=\"alert\"></div>\n");
      out.write("\n");
      out.write("            <form id=\"loginForm\" novalidate>\n");
      out.write("                <!-- Username -->\n");
      out.write("                <div class=\"mb-3\">\n");
      out.write("                    <label for=\"username\" class=\"form-label small fw-semibold text-secondary\">Username</label>\n");
      out.write("                    <div class=\"input-group\">\n");
      out.write("                        <span class=\"input-group-text bg-light text-muted border-end-0\"><i class=\"bi bi-person\"></i></span>\n");
      out.write("                        <input type=\"text\" class=\"form-control border-start-0 ps-0\" id=\"username\" name=\"username\" placeholder=\"Enter your username\" required autofocus autocomplete=\"username\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- Password -->\n");
      out.write("                <div class=\"mb-3\">\n");
      out.write("                    <div class=\"d-flex justify-content-between align-items-center mb-1\">\n");
      out.write("                        <label for=\"password\" class=\"form-label small fw-semibold text-secondary mb-0\">Password</label>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"input-group\">\n");
      out.write("                        <span class=\"input-group-text bg-light text-muted border-end-0\"><i class=\"bi bi-key\"></i></span>\n");
      out.write("                        <input type=\"password\" class=\"form-control border-start-0 border-end-0 ps-0\" id=\"password\" name=\"password\" placeholder=\"Enter your password\" required autocomplete=\"current-password\">\n");
      out.write("                        <button class=\"btn btn-outline-secondary border-start-0\" type=\"button\" id=\"togglePassword\" title=\"Show or hide password\">\n");
      out.write("                            <i class=\"bi bi-eye\"></i>\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- Remember Me / Info -->\n");
      out.write("                <div class=\"d-flex justify-content-between align-items-center mb-4\">\n");
      out.write("                    <div class=\"form-check\">\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"rememberMe\" checked>\n");
      out.write("                        <label class=\"form-check-label small text-muted\" for=\"rememberMe\">Session Cookie (HttpOnly)</label>\n");
      out.write("                    </div>\n");
      out.write("                    <span class=\"badge bg-light text-secondary border\">SHA-256 / PBKDF2</span>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- Submit Button -->\n");
      out.write("                <div class=\"d-grid mb-3\">\n");
      out.write("                    <button type=\"submit\" id=\"btnLogin\" class=\"btn btn-primary py-2 fs-6\">\n");
      out.write("                        <i class=\"bi bi-box-arrow-in-right me-2\"></i>Sign In\n");
      out.write("                    </button>\n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("\n");
      out.write("            <!-- Quick Demo Credentials for Reviewers / Interviewers -->\n");
      out.write("            <div class=\"mt-4 pt-3 border-top text-center\">\n");
      out.write("                <span class=\"small text-muted d-block mb-2 fw-semibold\">Quick-fill Demo Credentials:</span>\n");
      out.write("                <div class=\"d-flex justify-content-center gap-2 flex-wrap\">\n");
      out.write("                    <span class=\"demo-pill\" data-user=\"admin\" data-pass=\"Admin@123\" title=\"Full Administrator Privileges\">\n");
      out.write("                        <i class=\"bi bi-shield-check me-1 text-danger\"></i><strong>Admin</strong>\n");
      out.write("                    </span>\n");
      out.write("                    <span class=\"demo-pill\" data-user=\"jane_manager\" data-pass=\"Manager@123\" title=\"Manager Privileges\">\n");
      out.write("                        <i class=\"bi bi-award me-1 text-warning\"></i><strong>Manager</strong>\n");
      out.write("                    </span>\n");
      out.write("                    <span class=\"demo-pill\" data-user=\"john_doe\" data-pass=\"User@123\" title=\"Standard User Privileges\">\n");
      out.write("                        <i class=\"bi bi-person me-1 text-primary\"></i><strong>User</strong>\n");
      out.write("                    </span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Footer note -->\n");
      out.write("            <div class=\"text-center mt-3\">\n");
      out.write("                <small class=\"text-muted\" style=\"font-size: 0.75rem;\">\n");
      out.write("                    <i class=\"bi bi-database me-1\"></i>MySQL Backend &bull; Jersey REST &bull; JSP &bull; Ajax\n");
      out.write("                </small>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- jQuery 3.7.1 -->\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.7.1.min.js\"></script>\n");
      out.write("    <!-- Bootstrap 5.3 JS Bundle -->\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("    <!-- Authentication Logic -->\n");
      out.write("    <script src=\"assets/js/auth.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
